FROM node:18 AS build

RUN mkdir /app
WORKDIR /app
COPY ./services/manager/package.json  ./
COPY ./services/manager/package-lock.json ./
RUN npm install

RUN mkdir security
COPY ./security/public.pem ./security
COPY ./security/private.pem ./security
COPY ./services/manager ./
RUN npm run build

CMD [ "npm", "run" ,"dev"]